Jolly/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls')),
]

first/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from first import views


app_name = "first"


urlpatterns = [
    path('', views.index, name="index"),
    path('shop/', views.shop, name="shop"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    # path('contact/', views.shop_single, name="shop-single"),
    path('shop-single/<int:product_id>/', views.shop_single, name='shop-single'),
    path('like/<int:product_id>/', views.like_product, name='like_product'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('viewcart/', views.viewcart, name='viewcart'),
    path('remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    path('pay/', views.pay, name='pay'),
    path('confirm_payment/', views.confirm_payment, name='confirm_payment'),

                  path('login/', views.user_login, name='login'),
                  path('logout/', views.user_logout, name='logout'),
                  path('register/', views.user_register, name='signup'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script src="{% static 'js/forms.js' %}" defer></script>
    <title>Login</title>
</head>
<body>

    <div class="container">
        <h2>Login</h2>

        <form method="post" action="{% url 'first:login' %}">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="error-message">{{ form.non_field_errors.as_text }}</div>
            {% endif %}

            {{ form.username.label_tag }}
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error-message">{{ form.username.errors.0 }}</div>
            {% endif %}

            {{ form.password.label_tag }}
            {{ form.password }}
            {% if form.password.errors %}
                <div class="error-message">{{ form.password.errors.0 }}</div>
            {% endif %}

            <button type="submit">Login</button>
        </form>

        <p>Don't have an account? <a href="{% url 'first:signup' %}">Register here</a>/<a href="/">Home</a></p>
    </div>

</body>
</html>

templates/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script src="{% static 'js/forms.js' %}" defer></script>
</head>
<body>
    <div class="container">
    <h2>Logout</h2>
    <p>{{ messages }}</p>
    </div>

</body>
</html>

templates/pay.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" />
{#    <title>{% block title %}View Cart{% endblock %}</title>#}
</head>
<body>

<div class="payment-confirmation">
    <h2>Payment Confirmation</h2>
    <p>Total Amount: ${{ total_amount }}</p>

    <form method="post" action="{% url 'first:confirm_payment' %}">
        {% csrf_token %}
        <label for="phone_number">Enter your phone number:</label>
        <input type="text" name="phone_number" class="payment-input" required>
        <button type="submit" class="checkout-button">Confirm Payment</button>
    </form>
</div>
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script src="{% static 'js/forms.js' %}" defer></script>
    <title>Register</title>
</head>
<body>

    <div class="container">
        <h2>Register</h2>

        <form id="register-form" method="post" action="{% url 'first:signup' %}">
            {% csrf_token %}

            {% if form.non_field_errors %}
                <div class="error-message">{{ form.non_field_errors.as_text }}</div>
            {% endif %}

            {{ form.username.label_tag }}
            {{ form.username }}
            {% if form.username.errors %}
                <div class="error-message">{{ form.username.errors.0 }}</div>
            {% endif %}

            {{ form.email.label_tag }}
            {{ form.email }}
            {% if form.email.errors %}
                <div class="error-message">{{ form.email.errors.0 }}</div>
            {% endif %}

            {{ form.password1.label_tag }}
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="error-message">{{ form.password1.errors.0 }}</div>
            {% endif %}

            {{ form.password2.label_tag }}
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="error-message">{{ form.password2.errors.0 }}</div>
            {% endif %}

            <button type="submit">Register</button>
        </form>

        <p>Already have an account? <a href="{% url 'first:login' %}">Login here</a>/<a href="/">Home</a></p>
    </div>

</body>
</html>

templates/viewcart.html
{% load static %}

<!-- templates/viewcart.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" />
    <title>{% block title %}View Cart{% endblock %}</title>
</head>
<body>

    <div class="container">
        <h1>Your Shopping Cart</h1>
       <div id="cart-messages-container">
            {% for message in messages %}
                <div class="{% if message.tags %}alert alert-{{ message.tags }}{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>     {% if user_cart_items %}
            <form method="post" action="{% url 'first:remove_from_cart' %}">
                {% csrf_token %}
                {% for cart_item in user_cart_items %}
                    <div class="cart-item">
                        <h3>{{ cart_item.product.title }}</h3>
                        <p>Price: ${{ cart_item.product.price }}</p>
                        <p>Quantity: {{ cart_item.quantity }}</p>
                        <!-- Add other product details as needed -->

                        <!-- Include a hidden field for the cart item ID -->
                        <input type="hidden" name="cart_item_id" value="{{ cart_item.id }}">

                        <!-- Add a "Remove from Cart" button -->
                        <button type="submit" name="remove_from_cart_button" class="cart-item-remove">Remove from Cart</button>
                    </div>
                {% endfor %}
            </form>

            <!-- "Pay" button -->
            <button onclick="openPayModal()" class="checkout-button">Pay</button>
{#            <p>Total Amount: ${{ total_amount }}</p>#}

            <!-- Include the Pay modal -->
            <div id="payModal" class="modal">
                <div class="modal-content">
                    <!-- Include the pay.html template here -->
                    {% include 'pay.html' %}
                    <button onclick="closePayModal()" class="checkout-button">Close</button>
                </div>
            </div>
        {% else %}
            <p>Your cart is empty.</p>
        {% endif %}

        <!-- Include a link to the main shop page -->
        <a href="{% url 'first:shop' %}" class="continue-shopping-link">Continue Shopping</a>
    </div>

    <script>
        function openPayModal() {
            document.getElementById('payModal').style.display = 'block';
        }

        function closePayModal() {
            document.getElementById('payModal').style.display = 'none';
        }
        setTimeout(function() {
            var cartMessagesContainer = document.getElementById('cart-messages-container');
            if (cartMessagesContainer) {
                cartMessagesContainer.style.display = 'none';
            }
        }, 10000); // 10 seconds
    </script>

</body>
</html>